### ISSUE TITLE
Depricated package versions 

### ISSUE THREAD

**Issue by lelouchB** [insidesherpa/shiptivitas-1#5]
When tried to run npm start,
Gave lot of errors about how peer dependencies are not there and packages are of older versions
Trying to fix that, if anyone can help??

**Comment by hmuhammadazeem** [comment]
Hey, did you run "npm install" before running npm start? And can you show me console output/errors list?

**Comment by lelouchB** [comment]
yeah I did that and tried to change the package versions too but nothing worked

**Comment by lelouchB** [comment]
I'll add a screenshot of the error soon
